FROM node:18-alpine AS build-env

WORKDIR /app
COPY package.json ./

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN pnpm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ARG URL
ARG RSS
ARG CACHE
ARG PROXY
ARG REDIS_URL
ARG ITEMS_PER_RSS
ARG FETCH_PROVIDERS
ARG PROVIDERS_LIST_URL
ARG EXPIRE_TIME_FOR_RSS
ARG EXPIRE_TIME_FOR_POST
ARG FETCH_PROVIDERS_EVERY
ARG EXPIRE_TIME_FOR_POSTS
ARG SLEEP_TIME_PER_REQUEST
ARG USE_HEADLESS_PROVIDERS
ARG EXPIRE_TIME_FOR_STORIES
ARG EXPIRE_TIME_FOR_PROFILE

# Définir les variables d'environnement pour la phase de build
ENV URL=$URL
ENV RSS=$RSS
ENV CACHE=$CACHE
ENV PROXY=$PROXY
ENV REDIS_URL=$REDIS_URL
ENV ITEMS_PER_RSS=$ITEMS_PER_RSS
ENV FETCH_PROVIDERS=$FETCH_PROVIDERS
ENV PROVIDERS_LIST_URL=$PROVIDERS_LIST_URL
ENV EXPIRE_TIME_FOR_RSS=$EXPIRE_TIME_FOR_RSS
ENV EXPIRE_TIME_FOR_POST=$EXPIRE_TIME_FOR_POST
ENV FETCH_PROVIDERS_EVERY=$FETCH_PROVIDERS_EVERY
ENV EXPIRE_TIME_FOR_POSTS=$EXPIRE_TIME_FOR_POSTS
ENV SLEEP_TIME_PER_REQUEST=$SLEEP_TIME_PER_REQUEST
ENV USE_HEADLESS_PROVIDERS=$USE_HEADLESS_PROVIDERS
ENV EXPIRE_TIME_FOR_STORIES=$EXPIRE_TIME_FOR_STORIES
ENV EXPIRE_TIME_FOR_PROFILE=$EXPIRE_TIME_FOR_PROFILE

# Construire l'application Next.js
RUN pnpm run build

RUN pnpm run build

FROM gcr.io/distroless/nodejs18-debian11:nonroot

WORKDIR /app

COPY --from=build-env /app/next.config.mjs ./
COPY --from=build-env /app/env.mjs ./
COPY --from=build-env /app/.next /app/.next
COPY --from=build-env /app/node_modules /app/node_modules
COPY --from=build-env /app/public /app/public

CMD ["./node_modules/next/dist/bin/next", "start"]
